#include "init_i2s.h"

i2s_chan_handle_t rx_handle;
i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);

void init_microphone(void){
    chan_cfg.auto_clear = true; // Auto clear the legacy data in the DMA buffer
    chan_cfg.dma_desc_num = INIT_I2S_DMA_DESC_NUM;
    chan_cfg.dma_frame_num = INIT_I2S_DMA_FRAME_NUM;
    /* Allocate a new RX channel and get the handle of this channel */
    ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, NULL, &rx_handle));
    /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
     * These two helper macros are defined in `i2s_std.h` which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or updating */
    // 1. Setup the slot configuration for a 64*fs BCLK with a 1-clock delay
    i2s_std_slot_config_t slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(
        I2S_DATA_BIT_WIDTH_24BIT,   // Hardware extracts 24 bits of valid audio data
        I2S_SLOT_MODE_STEREO        // 2 slots (Left + Right) -> 2 * 32 = 64 * fs BCLK
    );
    // Force driver to focus strictly on the Left slot
    slot_cfg.slot_mask = I2S_STD_SLOT_BOTH;
    slot_cfg.slot_bit_width = I2S_SLOT_BIT_WIDTH_32BIT;
    slot_cfg.ws_width =  I2S_SLOT_BIT_WIDTH_32BIT;
    // 2. Setup the clock configuration using the precise Audio PLL
    i2s_std_clk_config_t clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(INIT_AUDIO_SAMPLE_RATE);
    clk_cfg.mclk_multiple = I2S_MCLK_MULTIPLE_384;      // Perfect bridge for 3 and 64
    clk_cfg.bclk_div = 6; // bclk_div = MCLK / BCLK
    //3. combine into one setup:
    i2s_std_config_t std_cfg = {
        .clk_cfg = clk_cfg,
        .slot_cfg = slot_cfg,
        .gpio_cfg = {
            .mclk = INIT_I2S_MCK_IO,
            .bclk = INIT_I2S_BCK_IO,
            .ws = INIT_I2S_WS_IO,
            .dout = INIT_I2S_DO_IO,
            .din = INIT_I2S_DI_IO,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    /* Initialize the channel */
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(rx_handle, &std_cfg));
    /* Before reading data, start the RX channel first */
    ESP_ERROR_CHECK(i2s_channel_enable(rx_handle));
}